version: '3.8'

services:
  graphql-server:
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    image: product-api-graphql
    restart: on-failure
    stdin_open: true
    tty: true
